sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: sky-idea-project
    access-key-secret: twjpGvYGwvofJrwdOWB2GmqJ0qCmJx
    access-key-id: LTAI5tB8hRfLyuau8npMhkgE
